[installation.package_managers.dpkg]
title = "DPKG"
archs = ["x86_64", "ARM64", "ARMv7"]

[installation.package_managers.homebrew]
title = "Homebrew"
archs = ["x86_64"]

[installation.package_managers.nix]
title = "Nix"
archs = ["x86_64"]

[installation.package_managers.rpm]
title = "RPM"
archs = ["x86_64"]

[installation.package_managers.msi]
title = "MSI"
archs = ["x86_64"]
